import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Get all users who have opted in (stored in their updateMe data)
    const allUsers = await base44.asServiceRole.entities.User.list();

    const month = new Date().toLocaleString("en-US", { month: "long", year: "numeric" });
    let sent = 0;

    for (const user of allUsers) {
      // Check opt-in flag stored on user record
      if (!user.monthly_report_opt_in) continue;
      if (!user.email) continue;

      // Fetch their stocks
      const stocks = await base44.asServiceRole.entities.Stock.filter({ created_by_id: user.id });
      if (!stocks.length) continue;

      const totalValue = stocks.reduce((s, stock) => s + (stock.current_price || 0) * stock.quantity, 0);
      const totalCost = stocks.reduce((s, stock) => s + stock.purchase_price * stock.quantity, 0);
      const totalGain = totalValue - totalCost;
      const totalGainPct = totalCost > 0 ? ((totalGain / totalCost) * 100).toFixed(2) : "0.00";

      const holdingsRows = stocks.map(s => {
        const val = (s.current_price || 0) * s.quantity;
        const cost = s.purchase_price * s.quantity;
        const gain = val - cost;
        const pct = cost > 0 ? ((gain / cost) * 100).toFixed(2) : "0.00";
        return `• ${s.ticker} (${s.company_name}): ${s.quantity} shares @ $${s.purchase_price.toFixed(2)} avg — Value: $${val.toFixed(2)} — P&L: ${gain >= 0 ? "+" : ""}$${gain.toFixed(2)} (${gain >= 0 ? "+" : ""}${pct}%)`;
      }).join("\n");

      // Fetch transactions for the past month
      const txns = await base44.asServiceRole.entities.StockTransaction.filter({ created_by_id: user.id }, "-created_date", 50);
      const oneMonthAgo = new Date();
      oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
      const recentTxns = txns.filter(t => new Date(t.created_date) >= oneMonthAgo);

      const txnRows = recentTxns.length > 0
        ? recentTxns.map(t => {
            const date = new Date(t.created_date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
            const action = t.type === "buy" ? "🟢 BUY " : "🔴 SELL";
            return `${action}  ${t.ticker} — ${t.quantity} shares @ $${t.price?.toFixed(2)} = $${t.total?.toFixed(2)}  [${date}]`;
          }).join("\n")
        : "No transactions this month.";

      const body = `Hi ${user.full_name || "there"},\n\nHere is your StockPulse portfolio performance report for ${month}.\n\n📊 PORTFOLIO SUMMARY\nTotal Value: $${totalValue.toFixed(2)}\nTotal Cost Basis: $${totalCost.toFixed(2)}\nOverall P&L: ${totalGain >= 0 ? "+" : ""}$${totalGain.toFixed(2)} (${totalGain >= 0 ? "+" : ""}${totalGainPct}%)\n\n📋 HOLDINGS\n${holdingsRows}\n\n🕒 TRANSACTIONS THIS MONTH\n${txnRows}\n\n---\nThis report was generated by StockPulse. Market data may be delayed.\n\nHappy investing! 📈\nThe StockPulse Team`;

      await base44.asServiceRole.integrations.Core.SendEmail({
        to: user.email,
        subject: `Your StockPulse Monthly Report — ${month}`,
        body,
      });
      sent++;
    }

    return Response.json({ ok: true, sent });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});