import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const resendApiKey = process.env.RESEND_API_KEY;
const resendFromEmail = process.env.RESEND_FROM_EMAIL || "StockPulse <reports@yourdomain.com>";

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

async function sendEmail({ to, subject, body }) {
  if (!resendApiKey) {
    throw new Error("Missing RESEND_API_KEY");
  }

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${resendApiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: resendFromEmail,
      to,
      subject,
      text: body,
    }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Email send failed: ${errorText}`);
  }

  return res.json();
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    if (!supabaseUrl || !supabaseServiceRoleKey) {
      return res.status(500).json({ error: "Missing Supabase server environment variables" });
    }

    const month = new Date().toLocaleString("en-US", {
      month: "long",
      year: "numeric",
    });

    let sent = 0;

    const { data: users, error: usersError } = await supabase
      .from("profiles")
      .select("id, email, full_name, monthly_report_opt_in")
      .eq("monthly_report_opt_in", true);

    if (usersError) {
      throw usersError;
    }

    for (const user of users || []) {
      if (!user.email) continue;

      const { data: stocks, error: stocksError } = await supabase
        .from("stocks")
        .select("*")
        .eq("user_id", user.id);

      if (stocksError) {
        throw stocksError;
      }

      if (!stocks || !stocks.length) continue;

      const totalValue = stocks.reduce(
        (sum, stock) => sum + (stock.current_price || 0) * stock.quantity,
        0
      );

      const totalCost = stocks.reduce(
        (sum, stock) => sum + stock.purchase_price * stock.quantity,
        0
      );

      const totalGain = totalValue - totalCost;
      const totalGainPct =
        totalCost > 0 ? ((totalGain / totalCost) * 100).toFixed(2) : "0.00";

      const holdingsRows = stocks
        .map((stock) => {
          const val = (stock.current_price || 0) * stock.quantity;
          const cost = stock.purchase_price * stock.quantity;
          const gain = val - cost;
          const pct = cost > 0 ? ((gain / cost) * 100).toFixed(2) : "0.00";

          return `• ${stock.ticker} (${stock.company_name}): ${stock.quantity} shares @ 
$$
{stock.purchase_price.toFixed(
            2
          )} avg — Value:
$$
{val.toFixed(2)} — P&L: ${
            gain >= 0 ? "+" : ""
          }
$$
{gain.toFixed(2)} (${gain >= 0 ? "+" : ""}${pct}%)`;
        })
        .join("\n");

      const { data: txns, error: txnsError } = await supabase
        .from("stock_transactions")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false })
        .limit(50);

      if (txnsError) {
        throw txnsError;
      }

      const oneMonthAgo = new Date();
      oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);

      const recentTxns = (txns || []).filter(
        (t) => new Date(t.created_at) >= oneMonthAgo
      );

      const txnRows =
        recentTxns.length > 0
          ? recentTxns
              .map((t) => {
                const date = new Date(t.created_at).toLocaleDateString("en-US", {
                  month: "short",
                  day: "numeric",
                  year: "numeric",
                });
                const action = t.type === "buy" ? "🟢 BUY " : "🔴 SELL";

                return `${action}  ${t.ticker} — ${t.quantity} shares @
$$
{t.price?.toFixed(
                  2
                )} = 
$$
{t.total?.toFixed(2)}  [${date}]`;
              })
              .join("\n")
          : "No transactions this month.";

      const body = `Hi ${user.full_name || "there"},

Here is your StockPulse portfolio performance report for ${month}.

📊 PORTFOLIO SUMMARY
Total Value:
$$
{totalValue.toFixed(2)}
Total Cost Basis: 
$$
{totalCost.toFixed(2)}
Overall P&L: ${totalGain >= 0 ? "+" : ""}
$$
{totalGain.toFixed(2)} (${
        totalGain >= 0 ? "+" : ""
      }${totalGainPct}%)

📋 HOLDINGS
${holdingsRows}

🕒 TRANSACTIONS THIS MONTH
${txnRows}

---
This report was generated by StockPulse. Market data may be delayed.

Happy investing! 📈
The StockPulse Team`;

      await sendEmail({
        to: user.email,
        subject: `Your StockPulse Monthly Report — ${month}`,
        body,
      });

      sent++;
    }

    return res.status(200).json({ ok: true, sent });
  } catch (error) {
    return res.status(500).json({
      error: error?.message || "Internal server error",
    });
  }
}
