// Popular stock tickers with company names
export const POPULAR_TICKERS = [
  { ticker: "AAPL", name: "Apple Inc." },
  { ticker: "MSFT", name: "Microsoft Corporation" },
  { ticker: "GOOGL", name: "Alphabet Inc." },
  { ticker: "GOOG", name: "Alphabet Inc. Class C" },
  { ticker: "AMZN", name: "Amazon.com Inc." },
  { ticker: "NVDA", name: "NVIDIA Corporation" },
  { ticker: "META", name: "Meta Platforms Inc." },
  { ticker: "TSLA", name: "Tesla Inc." },
  { ticker: "BRK.B", name: "Berkshire Hathaway" },
  { ticker: "LLY", name: "Eli Lilly and Company" },
  { ticker: "AVGO", name: "Broadcom Inc." },
  { ticker: "JPM", name: "JPMorgan Chase & Co." },
  { ticker: "UNH", name: "UnitedHealth Group" },
  { ticker: "XOM", name: "Exxon Mobil Corporation" },
  { ticker: "V", name: "Visa Inc." },
  { ticker: "MA", name: "Mastercard Inc." },
  { ticker: "PG", name: "Procter & Gamble Co." },
  { ticker: "JNJ", name: "Johnson & Johnson" },
  { ticker: "COST", name: "Costco Wholesale" },
  { ticker: "HD", name: "The Home Depot Inc." },
  { ticker: "ABBV", name: "AbbVie Inc." },
  { ticker: "MRK", name: "Merck & Co. Inc." },
  { ticker: "CVX", name: "Chevron Corporation" },
  { ticker: "KO", name: "The Coca-Cola Company" },
  { ticker: "BAC", name: "Bank of America Corp." },
  { ticker: "WMT", name: "Walmart Inc." },
  { ticker: "PEP", name: "PepsiCo Inc." },
  { ticker: "ORCL", name: "Oracle Corporation" },
  { ticker: "NFLX", name: "Netflix Inc." },
  { ticker: "AMD", name: "Advanced Micro Devices" },
  { ticker: "ADBE", name: "Adobe Inc." },
  { ticker: "CRM", name: "Salesforce Inc." },
  { ticker: "TMO", name: "Thermo Fisher Scientific" },
  { ticker: "CSCO", name: "Cisco Systems Inc." },
  { ticker: "ACN", name: "Accenture plc" },
  { ticker: "ABT", name: "Abbott Laboratories" },
  { ticker: "INTC", name: "Intel Corporation" },
  { ticker: "INTU", name: "Intuit Inc." },
  { ticker: "TXN", name: "Texas Instruments" },
  { ticker: "QCOM", name: "Qualcomm Inc." },
  { ticker: "WFC", name: "Wells Fargo & Company" },
  { ticker: "AMGN", name: "Amgen Inc." },
  { ticker: "IBM", name: "IBM Corporation" },
  { ticker: "GS", name: "Goldman Sachs Group" },
  { ticker: "MS", name: "Morgan Stanley" },
  { ticker: "CAT", name: "Caterpillar Inc." },
  { ticker: "SPGI", name: "S&P Global Inc." },
  { ticker: "NOW", name: "ServiceNow Inc." },
  { ticker: "NEE", name: "NextEra Energy Inc." },
  { ticker: "RTX", name: "RTX Corporation" },
  { ticker: "BX", name: "Blackstone Inc." },
  { ticker: "SCHW", name: "Charles Schwab Corp." },
  { ticker: "DE", name: "Deere & Company" },
  { ticker: "UPS", name: "United Parcel Service" },
  { ticker: "BMY", name: "Bristol-Myers Squibb" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc." },
  { ticker: "SYK", name: "Stryker Corporation" },
  { ticker: "SBUX", name: "Starbucks Corporation" },
  { ticker: "GE", name: "GE Aerospace" },
  { ticker: "MDT", name: "Medtronic plc" },
  { ticker: "GILD", name: "Gilead Sciences Inc." },
  { ticker: "ADI", name: "Analog Devices Inc." },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals" },
  { ticker: "PLD", name: "Prologis Inc." },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals" },
  { ticker: "MMC", name: "Marsh & McLennan" },
  { ticker: "CB", name: "Chubb Limited" },
  { ticker: "SO", name: "Southern Company" },
  { ticker: "MO", name: "Altria Group Inc." },
  { ticker: "DUK", name: "Duke Energy Corporation" },
  { ticker: "ITW", name: "Illinois Tool Works" },
  { ticker: "AON", name: "Aon plc" },
  { ticker: "SLB", name: "Schlumberger Limited" },
  { ticker: "MU", name: "Micron Technology Inc." },
  { ticker: "KLAC", name: "KLA Corporation" },
  { ticker: "LRCX", name: "Lam Research Corporation" },
  { ticker: "AMAT", name: "Applied Materials Inc." },
  { ticker: "SNPS", name: "Synopsys Inc." },
  { ticker: "CDNS", name: "Cadence Design Systems" },
  { ticker: "MRVL", name: "Marvell Technology Inc." },
  { ticker: "PANW", name: "Palo Alto Networks" },
  { ticker: "CRWD", name: "CrowdStrike Holdings" },
  { ticker: "SNOW", name: "Snowflake Inc." },
  { ticker: "UBER", name: "Uber Technologies Inc." },
  { ticker: "LYFT", name: "Lyft Inc." },
  { ticker: "ABNB", name: "Airbnb Inc." },
  { ticker: "SHOP", name: "Shopify Inc." },
  { ticker: "SQ", name: "Block Inc." },
  { ticker: "PYPL", name: "PayPal Holdings Inc." },
  { ticker: "COIN", name: "Coinbase Global Inc." },
  { ticker: "SPOT", name: "Spotify Technology" },
  { ticker: "SNAP", name: "Snap Inc." },
  { ticker: "PINS", name: "Pinterest Inc." },
  { ticker: "TWTR", name: "Twitter / X Corp." },
  { ticker: "ZM", name: "Zoom Video Communications" },
  { ticker: "DOCU", name: "DocuSign Inc." },
  { ticker: "OKTA", name: "Okta Inc." },
  { ticker: "DDOG", name: "Datadog Inc." },
  { ticker: "NET", name: "Cloudflare Inc." },
  { ticker: "ZS", name: "Zscaler Inc." },
  { ticker: "PLTR", name: "Palantir Technologies" },
  { ticker: "ARM", name: "Arm Holdings plc" },
  { ticker: "SMCI", name: "Super Micro Computer" },
  { ticker: "TSM", name: "Taiwan Semiconductor" },
  { ticker: "ASML", name: "ASML Holding N.V." },
  { ticker: "SAP", name: "SAP SE" },
  { ticker: "NVO", name: "Novo Nordisk A/S" },
  { ticker: "SONY", name: "Sony Group Corporation" },
  { ticker: "TM", name: "Toyota Motor Corporation" },
  { ticker: "BABA", name: "Alibaba Group" },
  { ticker: "JD", name: "JD.com Inc." },
  { ticker: "PDD", name: "PDD Holdings Inc." },
  { ticker: "BIDU", name: "Baidu Inc." },
  { ticker: "SE", name: "Sea Limited" },
  { ticker: "MELI", name: "MercadoLibre Inc." },
  { ticker: "NU", name: "Nu Holdings Ltd." },
  { ticker: "SQ", name: "Block Inc." },
  { ticker: "SOFI", name: "SoFi Technologies" },
  { ticker: "HOOD", name: "Robinhood Markets" },
  { ticker: "RIVN", name: "Rivian Automotive" },
  { ticker: "LCID", name: "Lucid Group Inc." },
  { ticker: "NIO", name: "NIO Inc." },
  { ticker: "LI", name: "Li Auto Inc." },
  { ticker: "XPEV", name: "XPeng Inc." },
  { ticker: "F", name: "Ford Motor Company" },
  { ticker: "GM", name: "General Motors Company" },
  { ticker: "STLA", name: "Stellantis N.V." },
  { ticker: "BA", name: "Boeing Company" },
  { ticker: "LMT", name: "Lockheed Martin Corp." },
  { ticker: "NOC", name: "Northrop Grumman Corp." },
  { ticker: "GD", name: "General Dynamics Corp." },
  { ticker: "HII", name: "Huntington Ingalls" },
  { ticker: "RHM", name: "Rheinmetall AG" },
  { ticker: "DIS", name: "The Walt Disney Company" },
  { ticker: "CMCSA", name: "Comcast Corporation" },
  { ticker: "CHTR", name: "Charter Communications" },
  { ticker: "T", name: "AT&T Inc." },
  { ticker: "VZ", name: "Verizon Communications" },
  { ticker: "TMUS", name: "T-Mobile US Inc." },
  { ticker: "AMT", name: "American Tower Corp." },
  { ticker: "CCI", name: "Crown Castle Inc." },
  { ticker: "EQIX", name: "Equinix Inc." },
  { ticker: "DLR", name: "Digital Realty Trust" },
  { ticker: "O", name: "Realty Income Corp." },
  { ticker: "SPG", name: "Simon Property Group" },
  { ticker: "PSA", name: "Public Storage" },
  { ticker: "AVB", name: "AvalonBay Communities" },
  { ticker: "WY", name: "Weyerhaeuser Company" },
  { ticker: "WELL", name: "Welltower Inc." },
  { ticker: "ZG", name: "Zillow Group Inc." },
  { ticker: "Z", name: "Zillow Group Inc. C" },
  { ticker: "ONDS", name: "Ondas Holdings Inc." },
];