import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const FD_KEY=Deno.env.get("FINANCIAL_DATASETS_API_KEY")||"",XAI_KEY=Deno.env.get("XAI_API_KEY")||"",SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",STOCK_SYNC_SECRET=Deno.env.get("STOCK_SYNC_SECRET")||"",CACHE_HOURS=12,GROK_MODEL="grok-4.6";
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-sync-secret","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}}),text=(v:unknown)=>String(v??"").trim(),tickerOf=(v:unknown)=>text(v).toUpperCase();
const timestampSeconds=(v:unknown)=>{if(v===null||v===undefined||v==="")return null;const n=Number(v);if(Number.isFinite(n))return n>1e10?Math.floor(n/1000):Math.floor(n);const p=Date.parse(text(v));return Number.isFinite(p)?Math.floor(p/1000):null};
async function logGrokUsage(ticker:string,toolCalls:number,costTicks:number,metadata:Record<string,unknown>={}){const{error}=await db.from("grok_api_usage").insert({function_name:"refresh-watchlist-news",ticker,model:GROK_MODEL,purpose:"news-background",tool_calls:Math.max(0,Math.trunc(toolCalls||0)),cost_ticks:Math.max(0,Math.trunc(costTicks||0)),metadata});if(error)console.error("Grok usage log failed",error.message)}
function normalizeArticle(ticker:string,raw:any){const title=text(raw?.title??raw?.headline),url=text(raw?.url??raw?.article_url);if(!title||!/^https?:\/\//i.test(url))return null;const date=text(raw?.date??raw?.published_date??raw?.published_at??raw?.publishedAt??raw?.time);return{ticker,title,source:text(raw?.source??raw?.publisher),date,datetime:timestampSeconds(raw?.datetime??raw?.published_at??raw?.published_at_epoch??raw?.time??date),url,summary:text(raw?.summary??raw?.description),image:text(raw?.image??raw?.image_url)}}
async function tickerStillActive(ticker:string){const{data,error}=await db.from("watchlist_items").select("id").eq("ticker",ticker).limit(1);if(error)throw new Error(`Could not verify watchlist membership: ${error.message}`);return Array.isArray(data)&&data.length>0}
async function hasFreshCache(ticker:string){const{data,error}=await db.from("stock_news_cache").select("id").eq("ticker",ticker).gt("expires_at",new Date().toISOString()).limit(1);if(error)throw new Error(`Could not inspect news cache: ${error.message}`);return Array.isArray(data)&&data.length>0}
async function removeFromQueue(ticker:string){const{error}=await db.from("stock_news_refresh_queue").delete().eq("ticker",ticker);if(error)console.warn("Could not remove news refresh queue item",ticker,error.message)}
async function recordQueueFailure(ticker:string,message:string){const{data}=await db.from("stock_news_refresh_queue").select("attempts").eq("ticker",ticker).maybeSingle();const attempts=Number(data?.attempts??0)+1;await db.from("stock_news_refresh_queue").upsert({ticker,requested_at:new Date(Date.now()+Math.min(attempts,10)*60000).toISOString(),reason:"retry",attempts,last_error:message.slice(0,1000)},{onConflict:"ticker"})}
async function financialDatasetsNews(ticker:string,limit:number){if(!FD_KEY)throw new Error("Missing FINANCIAL_DATASETS_API_KEY.");const url=new URL("https://api.financialdatasets.ai/news");url.searchParams.set("ticker",ticker);url.searchParams.set("limit",String(limit));const response=await fetch(url,{headers:{Accept:"application/json","X-API-KEY":FD_KEY}});if(!response.ok)return[];const p=await response.json().catch(()=>({}));return(Array.isArray(p?.news)?p.news:[]).map((x:any)=>normalizeArticle(ticker,x)).filter(Boolean).slice(0,limit)}
function outputText(p:any){for(const item of Array.isArray(p?.output)?p.output:[]){if(item?.type!=="message")continue;for(const block of Array.isArray(item?.content)?item.content:[])if(block?.type==="output_text"&&text(block?.text))return text(block.text)}return""}
async function grokNews(ticker:string,limit:number){if(!XAI_KEY)throw new Error("Missing XAI_API_KEY.");const response=await fetch("https://api.x.ai/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${XAI_KEY}`},body:JSON.stringify({model:GROK_MODEL,input:[{role:"user",content:`Find up to ${limit} of the latest legitimate web news articles specifically about the CURRENT publicly traded company represented by U.S. ticker ${ticker}. Verify the current ticker/company identity and do not return articles about a former security that previously used the same ticker. Return only real article URLs discovered with web search. Prefer established financial, business, technology, wire-service, newspaper, and company-news sources. Use publication dates in YYYY-MM-DD format when available. Keep each summary to one short sentence.`}],tools:[{type:"web_search"}],max_turns:2,text:{format:{type:"json_schema",name:"stock_news_articles",strict:true,schema:{type:"object",properties:{articles:{type:"array",maxItems:limit,items:{type:"object",properties:{title:{type:"string"},source:{type:"string"},date:{type:"string"},url:{type:"string"},summary:{type:"string"}},required:["title","source","date","url","summary"],additionalProperties:false}}},required:["articles"],additionalProperties:false}}},max_output_tokens:1400,store:false})});const rawResponse=await response.text();let p:any={};try{p=rawResponse?JSON.parse(rawResponse):{}}catch{p={}}const costTicks=Number(p?.usage?.cost_in_usd_ticks||0),toolCalls=Number(p?.usage?.num_server_side_tools_used||0);await logGrokUsage(ticker,toolCalls,costTicks,{http_status:response.status,ok:response.ok});if(!response.ok)throw new Error(text(p?.error?.message??p?.error??p?.message??rawResponse)||`xAI status ${response.status}`);const raw=outputText(p);if(!raw)throw new Error("xAI returned no output_text.");let parsed:any;try{parsed=JSON.parse(raw)}catch{throw new Error("xAI returned invalid structured JSON.")}const seen=new Set<string>();const articles=(Array.isArray(parsed?.articles)?parsed.articles:[]).map((x:any)=>normalizeArticle(ticker,x)).filter((x:any)=>{if(!x)return false;const k=x.url.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,limit);return{articles,costTicks,toolCalls}}
async function cacheNews(ticker:string,articles:any[],provider:string,costTicks=0,toolCalls=0){if(!articles.length)return;const now=new Date(),expiresAt=new Date(now.getTime()+CACHE_HOURS*3600000).toISOString();const rows=articles.map((a:any)=>({ticker,title:a.title,source:a.source||null,published_date:a.date||null,published_at:a.datetime||null,url:a.url,summary:a.summary||null,image:a.image||null,provider,fetched_at:now.toISOString(),expires_at:expiresAt,grok_cost_ticks:provider==="grok-web-search"?costTicks:null,grok_tool_calls:provider==="grok-web-search"?toolCalls:null,updated_at:now.toISOString()}));const{error}=await db.from("stock_news_cache").upsert(rows,{onConflict:"url"});if(error)throw new Error(`Could not write news cache: ${error.message}`)}
async function nextTicker(){const{data,error}=await db.rpc("next_watchlist_news_ticker");if(error)throw new Error(`Could not select next watchlist ticker: ${error.message}`);return tickerOf(data)}
async function processTicker(ticker:string){if(!(await tickerStillActive(ticker))){await removeFromQueue(ticker);await db.from("stock_news_cache").delete().eq("ticker",ticker);return{ticker,status:"removed"}}if(await hasFreshCache(ticker)){await removeFromQueue(ticker);return{ticker,status:"fresh"}}try{const fd=await financialDatasetsNews(ticker,10);if(fd.length){await cacheNews(ticker,fd,"financial-datasets");await removeFromQueue(ticker);return{ticker,status:"cached",provider:"financial-datasets",articles:fd.length}}const grok=await grokNews(ticker,10);if(grok.articles.length){await cacheNews(ticker,grok.articles,"grok-web-search",grok.costTicks,grok.toolCalls);await removeFromQueue(ticker);return{ticker,status:"cached",provider:"grok-web-search",articles:grok.articles.length,grok_cost_ticks:grok.costTicks,grok_cost_usd:grok.costTicks/1e10,grok_tool_calls:grok.toolCalls}}await removeFromQueue(ticker);return{ticker,status:"no-news",provider:"none"}}catch(error){const message=error instanceof Error?error.message:"Unknown news refresh error.";await recordQueueFailure(ticker,message);return{ticker,status:"failed",error:message}}}
Deno.serve(async(request)=>{if(request.method==="OPTIONS")return new Response("ok",{headers:CORS});if(request.method!=="POST")return json({ok:false,error:"Method not allowed."},405);const receivedSecret=request.headers.get("x-sync-secret")||"";if(!STOCK_SYNC_SECRET||receivedSecret!==STOCK_SYNC_SECRET)return json({ok:false,error:"Unauthorized watchlist news refresh request."},401);if(!SUPABASE_URL||!SERVICE_KEY)return json({ok:false,error:"Supabase service credentials are unavailable."},503);const body=await request.json().catch(()=>({})),directTicker=tickerOf(body?.ticker);if(directTicker){const result=await processTicker(directTicker);return json({ok:true,processed:1,results:[result],finished_at:new Date().toISOString()})}const requestedBatchSize=Math.trunc(Number(body?.batchSize)||1),batchSize=Math.min(Math.max(requestedBatchSize,1),3),results:any[]=[],seen=new Set<string>();for(let i=0;i<batchSize;i++){const ticker=await nextTicker();if(!ticker||seen.has(ticker))break;seen.add(ticker);results.push(await processTicker(ticker))}return json({ok:true,processed:results.length,results,finished_at:new Date().toISOString()})});
