import { requireStockPulseAccess } from "../_shared/entitlement.ts";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const FD_KEY=Deno.env.get("FINANCIAL_DATASETS_API_KEY")||"",XAI_KEY=Deno.env.get("XAI_API_KEY")||"",SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",GROK_MODEL="grok-4.6",FD_FRESH_HOURS=24,GROK_COOLDOWN_HOURS=12;
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}}),text=(v:any)=>String(v??"").trim(),tickerOf=(v:any)=>text(v).toUpperCase();
const ts=(v:any)=>{if(v===null||v===undefined||v==="")return null;const n=Number(v);if(Number.isFinite(n))return n>1e10?Math.floor(n/1000):Math.floor(n);const p=Date.parse(text(v));return Number.isFinite(p)?Math.floor(p/1000):null};
function article(t:string,r:any){const title=text(r?.title??r?.headline),url=text(r?.url??r?.article_url);if(!title||!/^https?:\/\//i.test(url))return null;const date=text(r?.date??r?.published_date??r?.published_at??r?.publishedAt??r?.time);return{ticker:t,title,headline:title,source:text(r?.source??r?.publisher),date,published_date:date,datetime:ts(r?.datetime??r?.published_at??r?.time??date),url,article_url:url,summary:text(r?.summary??r?.description),image:text(r?.image??r?.image_url)}}
function payload(t:string,a:any[],provider:string,cached:boolean,extra:any={}){return{ticker:t,articles:a,news:a,data:{ticker:t,articles:a,news:a},provider,cached,...extra}}
async function cachedNews(t:string,limit:number){const{data,error}=await db.from("stock_news_cache").select("ticker,title,source,published_date,published_at,url,summary,image,provider,fetched_at,expires_at").eq("ticker",t).order("published_at",{ascending:false,nullsFirst:false}).limit(limit);if(error)return[];return(data||[]).map((x:any)=>article(t,{...x,date:x.published_date,datetime:x.published_at})).filter(Boolean)}
async function latestFetch(t:string){const{data}=await db.from("stock_news_cache").select("fetched_at,provider").eq("ticker",t).order("fetched_at",{ascending:false}).limit(1).maybeSingle();return data||null}
async function grokRecentlyUsed(t:string){const cutoff=new Date(Date.now()-GROK_COOLDOWN_HOURS*3600000).toISOString();const{data}=await db.from("grok_api_usage").select("id").eq("ticker",t).eq("purpose","news").gte("created_at",cutoff).limit(1);return!!data?.length}
async function logGrok(t:string,tools:number,cost:number){await db.from("grok_api_usage").insert({function_name:"stock-news",ticker:t,model:GROK_MODEL,purpose:"news",tool_calls:tools||0,cost_ticks:cost||0,metadata:{background_refresh:true}})}
async function fdNews(t:string,limit:number){if(!FD_KEY)return[];const u=new URL("https://api.financialdatasets.ai/news");u.searchParams.set("ticker",t);u.searchParams.set("limit",String(limit));const r=await fetch(u,{headers:{Accept:"application/json","X-API-KEY":FD_KEY}});if(!r.ok)return[];const p=await r.json().catch(()=>({}));const a=Array.isArray(p?.news)?p.news:Array.isArray(p?.articles)?p.articles:[];return a.map((x:any)=>article(t,x)).filter(Boolean).slice(0,limit)}
function outputText(p:any){if(text(p?.output_text))return text(p.output_text);for(const i of Array.isArray(p?.output)?p.output:[])for(const b of Array.isArray(i?.content)?i.content:[])if(b?.type==="output_text"&&text(b?.text))return text(b.text);return""}
async function grokNews(t:string,limit:number){if(!XAI_KEY)return{articles:[],costTicks:0,toolCalls:0};const r=await fetch("https://api.x.ai/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${XAI_KEY}`},body:JSON.stringify({model:GROK_MODEL,input:[{role:"user",content:`Find up to ${limit} latest legitimate web news articles specifically about current U.S. ticker ${t}. Return real article URLs, source, date YYYY-MM-DD, and one-sentence summary.`}],tools:[{type:"web_search"}],max_turns:2,text:{format:{type:"json_schema",name:"stock_news_articles",strict:true,schema:{type:"object",properties:{articles:{type:"array",maxItems:limit,items:{type:"object",properties:{title:{type:"string"},source:{type:"string"},date:{type:"string"},url:{type:"string"},summary:{type:"string"}},required:["title","source","date","url","summary"],additionalProperties:false}}},required:["articles"],additionalProperties:false}}},max_output_tokens:1400,store:false})});const raw=await r.text();let p:any={};try{p=JSON.parse(raw)}catch{}const cost=Number(p?.usage?.cost_in_usd_ticks||0),tools=Number(p?.usage?.num_server_side_tools_used||0);await logGrok(t,tools,cost);if(!r.ok)return{articles:[],costTicks:cost,toolCalls:tools};let parsed:any={};try{parsed=JSON.parse(outputText(p))}catch{}return{articles:(parsed?.articles||[]).map((x:any)=>article(t,x)).filter(Boolean).slice(0,limit),costTicks:cost,toolCalls:tools}}
async function cache(t:string,a:any[],provider:string,cost=0,tools=0){if(!a.length)return;const now=new Date(),expires=new Date(now.getTime()+FD_FRESH_HOURS*3600000).toISOString();await db.from("stock_news_cache").upsert(a.map((x:any)=>({ticker:t,title:x.title,source:x.source||null,published_date:x.date||null,published_at:x.datetime||null,url:x.url,summary:x.summary||null,image:x.image||null,provider,fetched_at:now.toISOString(),expires_at:expires,grok_cost_ticks:provider==="grok-web-search"?cost:null,grok_tool_calls:provider==="grok-web-search"?tools:null,updated_at:now.toISOString()})),{onConflict:"url"})}
async function refresh(t:string,limit:number){try{const fd=await fdNews(t,limit);if(fd.length){await cache(t,fd,"financial-datasets");return}if(await grokRecentlyUsed(t))return;const g=await grokNews(t,limit);if(g.articles.length)await cache(t,g.articles,"grok-web-search",g.costTicks,g.toolCalls)}catch(e){console.error("background news refresh",t,e)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({error:"Method not allowed"},405);const access=await requireStockPulseAccess(req);if(!access.ok)return json({error:access.error},access.status);try{const b=await req.json().catch(()=>({})),t=tickerOf(b?.ticker),limit=Math.min(Math.max(Math.floor(Number(b?.limit)||10),1),10);if(!t)return json({error:"Ticker is required"},400);const old=await cachedNews(t,limit),last=await latestFetch(t);if(old.length){const age=last?.fetched_at?Date.now()-new Date(last.fetched_at).getTime():Infinity;if(age>FD_FRESH_HOURS*3600000)EdgeRuntime.waitUntil(refresh(t,limit));return json(payload(t,old,"cache",true,{refreshing:age>FD_FRESH_HOURS*3600000}))}const fd=await fdNews(t,limit);if(fd.length){await cache(t,fd,"financial-datasets");return json(payload(t,fd,"financial-datasets",false))}if(await grokRecentlyUsed(t))return json(payload(t,[],"none",false,{grok_cooldown:true}));const g=await grokNews(t,limit);if(g.articles.length)await cache(t,g.articles,"grok-web-search",g.costTicks,g.toolCalls);return json(payload(t,g.articles,g.articles.length?"grok-web-search":"none",false,{grok_tool_calls:g.toolCalls}))}catch(e){return json({error:e instanceof Error?e.message:"News request failed"},500)}});