create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null check (char_length(event_name) between 1 and 80),
  session_id text not null check (char_length(session_id) between 1 and 80),
  route text null,
  platform text null,
  app_version text null,
  properties jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

comment on table public.analytics_events is
  'First-party StockPulse product analytics events used for DAU, sessions, feature usage, retention, and power-user analysis.';

create index if not exists analytics_events_user_time_idx
  on public.analytics_events (user_id, occurred_at desc);

create index if not exists analytics_events_name_time_idx
  on public.analytics_events (event_name, occurred_at desc);

create index if not exists analytics_events_session_idx
  on public.analytics_events (session_id, occurred_at);

alter table public.analytics_events enable row level security;

drop policy if exists "Users can insert own analytics events"
  on public.analytics_events;

create policy "Users can insert own analytics events"
  on public.analytics_events
  for insert
  to authenticated
  with check (auth.uid() = user_id);
